/**
 *  * SCENARIO 3: Migration (Move Pages to Database)
  * Moves pages from the Old Parent Page -> Notion Database
   */
   function runMigrationScenario() {
     const oldParentId = CONFIG.NOTION.OLD_PARENT_PAGE_ID;
       const newDbId = CONFIG.NOTION.DB_ID;

         if (!oldParentId || !newDbId) {
             Logger.log("Migration Skipped: ID configuration missing.");
                 return;
                   }

                     Logger.log("Checking for pages to migrate from Parent: " + oldParentId);

                       try {
                           // 1. Get Children of the Old Parent Page
                               const children = getNotionBlockChildren(oldParentId);
                                   
                                       let processedCount = 0;

                                           for (const block of children) {
                                                 // Check if it is a page and NOT archived (in trash)
                                                       if (block.type === 'child_page' && !block.archived) {
                                                               
                                                                       const pageTitle = block.child_page.title;
                                                                               const pageId = block.id;

                                                                                       Logger.log("Attempting to migrate: '" + pageTitle + "' (" + pageId + ")");
                                                                                               
                                                                                                       // 2. Prepare Payload
                                                                                                               // We map the title to the specific column name defined in CONFIG ('ID')
                                                                                                                       const properties = {};
                                                                                                                               properties[CONFIG.NOTION.PROPS.TITLE_COLUMN] = {
                                                                                                                                         "title": [ { "text": { "content": pageTitle } } ] 
                                                                                                                                                 };

                                                                                                                                                         const payload = {
                                                                                                                                                                   "parent": { "database_id": newDbId },
                                                                                                                                                                             "properties": properties
                                                                                                                                                                                     };

                                                                                                                                                                                             try {
                                                                                                                                                                                                       // 3. Send Update
                                                                                                                                                                                                                 const response = patchNotionPage(pageId, payload);
                                                                                                                                                                                                                           
                                                                                                                                                                                                                                     // 4. VERIFICATION
                                                                                                                                                                                                                                               // Check if parent ID matches the target Database ID
                                                                                                                                                                                                                                                         const newParentId = response.parent.database_id || response.parent.page_id;
                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                             // Normalize IDs (remove dashes) for comparison
                                                                                                                                                                                                                                                                                       const normNewParent = newParentId ? newParentId.replace(/-/g, '') : '';
                                                                                                                                                                                                                                                                                                 const normTargetDb = newDbId.replace(/-/g, '');

                                                                                                                                                                                                                                                                                                           if (normNewParent === normTargetDb) {
                                                                                                                                                                                                                                                                                                                        Logger.log("VERIFIED SUCCESS: Page moved to Database.");
                                                                                                                                                                                                                                                                                                                                     processedCount++;
                                                                                                                                                                                                                                                                                                                                               } else {
                                                                                                                                                                                                                                                                                                                                                            // If this logs, it means Notion accepted the request but didn't actually move it.
                                                                                                                                                                                                                                                                                                                                                                         // This usually happens if the property name ("ID") is still slightly different 
                                                                                                                                                                                                                                                                                                                                                                                      // (e.g., "id" vs "ID" or has a space "ID ").
                                                                                                                                                                                                                                                                                                                                                                                                   Logger.log("WARNING: API returned 200, but parent did not update. Current parent: " + JSON.stringify(response.parent));
                                                                                                                                                                                                                                                                                                                                                                                                                writeToLogSheet("Scenario 3 Migration", "Move Failed Silent", "Page: " + pageTitle + " Parent mismatch.");
                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (moveError) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            Logger.log("Failed to move page " + pageId + ": " + moveError.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      writeToLogSheet("Scenario 3 Migration", "Move Failed", moveError.toString());
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (processedCount === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Logger.log("No migratable child pages found in this batch (Limit 10).");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Logger.log('Migration Error: ' + e.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                writeToLogSheet("Scenario 3 Migration", "General Error", e.toString());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }



 